name: Build


on:
  deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${21.x}
      uses: actions/setup-node@v3
      with:
        node-version: 21.x

    - name: Build
      run: |
        cd frontend
        npm install
        npm run prod
        cd ../backend
        npm run build
        
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
      env:
          GHR_COMPRESS: zip
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}